name: 🎉 Deploy to GitHub Pages

# Grant the built-in token permission to push & publish
permissions:
  contents: write    # allow commits & pushes
  pages:    write    # allow Pages publishing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your entire repo (this brings in intakedb.db at root)
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) Install dependencies (if you actually need them for a build)
      - name: Install dependencies
        run: npm ci

      # 3) Build (no-op or your real build)
      - name: Build
        run: npm run build

      # 4) Push the entire working directory (including intakedb.db) to gh-pages
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
